### ISSUE TITLE
App crashes when trying to analyze differential expression in protein example dataset with DESeq2

### ISSUE THREAD

**Issue by evanjh19** [wejlab/BatchQC#34]
Selecting the button to analyze differential expression with the protein example dataset loaded into BatchQC and "DESeq2" chosen as the analysis method parameter will cause the app to crash. An input data check needs to be added to server_06_differentialExpression.R that ensures the dataset fits DESeq2's usage before analysis is run.

**Comment by jessmcc22** [comment]
DESeq2 doesn't work for any of our example data, but perhaps for mockSCE()
