### ISSUE TITLE
Additional DE Analysis Method Options

### ISSUE THREAD

**Issue by evanjh19** [wejlab/BatchQC#43]
Additional DE analysis method options need to be implemented (t-test, wilcoxon rank-sum, limma). Resolving this issue will require significant changes to DifferentialExpression.R and server_07_differentialExpression.R. Currently, handling of DE analysis inputs and DE analysis results is specific to the DESeq2 package. This code needs to be made flexible enough to handle data in multiple formats for additional analysis methods.

**Comment by jessmcc22** [comment]
Examples need to be created for all DE analysis functions (including volcano plot) once working

**Comment by jessmcc22** [comment]
Files have been restructured and limma has been included. Other methods to come in the future
